-- ============================================================
-- REMEDIATION: Portal B2B session token storage
-- Audit finding: api/pedido.js accepted orders from any HTTP
-- client with no authentication. The UUID token generated by
-- otp-verify.js was never stored or validated server-side.
--
-- Fix: store session tokens in portal_sessions table.
-- api/pedido.js validates the token before accepting orders.
-- Safe to re-run (CREATE TABLE IF NOT EXISTS).
-- ============================================================

CREATE TABLE IF NOT EXISTS portal_sessions (
  id          TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::text,
  token       TEXT        NOT NULL UNIQUE,
  cliente_id  TEXT        NOT NULL,
  tel         TEXT        NOT NULL,
  org_id      TEXT        NOT NULL DEFAULT 'aryes',
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup by token (the hot path on every order)
CREATE INDEX IF NOT EXISTS idx_portal_sessions_token
  ON portal_sessions (token, expires_at DESC);

-- Auto-cleanup: delete sessions older than 30 days
-- (run manually or via pg_cron if available)
-- DELETE FROM portal_sessions WHERE expires_at < NOW() - INTERVAL '30 days';

-- RLS: anon can insert (otp-verify uses anon/service key)
--      nobody can select via REST (validation done server-side only)
ALTER TABLE portal_sessions ENABLE ROW LEVEL SECURITY;

-- Only the service role (used by serverless functions) can read/write.
-- No authenticated or anon REST access — all access is via API functions.
-- This prevents clients from reading or forging session tokens via REST.
CREATE POLICY "portal_sessions_service_only" ON portal_sessions
  AS RESTRICTIVE
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);
